### ISSUE TITLE
How to properly get access to the InCites API?

### ISSUE THREAD

**Issue by mmagaldi77** [Clarivate-SAR/incites-retrieve#2]
@gneissone Hi I've just registered a new application on my clarivate user page specifically targeting incites-retrieve. How can I link the InCites API? I do not see it in the list of available APIs. Access is needed for selecting best papers in my institute for the Italian evaluation of research (VQR15-19). Main parameters needed are: papers by authors belonging to the institute, number of citations impact factors and quartiles (both most recent and year of publication).

Thanks in advance for any help

**Comment by gneissone** [comment]
Hi @mmagaldi77, access to InCites is often through your library, though it varies between institutions. I'll track down your account manager and ask them to reach out to you directly. Thanks!
